version: "2"

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid:/etc/selenoid
      - ./selenoid/logs:/opt/selenoid/logs
      - ./selenoid/video:/opt/selenoid/video
    command: [
      "-conf",
      "/etc/selenoid/browsers.json",
      "-container-network",
      "test-net",
      "-limit",
      "8",
      #        "-save-all-logs",
      #        "-capture-driver-logs",
      "-video-output-dir",
      "/opt/selenoid/video",
      "-log-output-dir",
      "/opt/selenoid/logs",
    ]

  web:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "80:80"

  test-chrome:
    extends:
      file: test-run.yml
      service: test-run
    environment:
      - browser=Chrome
      - testFilter=IgnoreInBrowser!=Chrome
  
  test-firefox:
    extends:
      file: test-run.yml
      service: test-run
    environment:
      - browser=Firefox
      - testFilter=IgnoreInBrowser!=Firefox

networks:
  default:
    name: test-net
