version: "2"

services:
  test-run:
    build:
      context: .
    environment:
      - TEST_ENVIRONMENT=${TEST_ENVIRONMENT}
      - isSelenoid=true
      - selenoidHubUrl=http://selenoid:4444/wd/hub
      - baseUrl=${BASE_URL}
      - browser=${BROWSER}    
    depends_on:
      - web
      - selenoid