version: "2"

services:
  test-run:
    build:
      context: .
    environment:
      - TEST_ENVIRONMENT=${TEST_ENVIRONMENT}
      - TestSettings__isSelenoid=true
      - TestSettings__selenoidHubUrl=http://selenoid:4444/wd/hub
      - TestSettings__baseUrl=${BASE_URL}
      - TestSettings__browser=${BROWSER}
    depends_on:
      - web
      - selenoid